services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/sql_app.db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
